# Generated by Django 6.0.3 on 2026-03-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowwow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество отзывов'),
        ),
    ]
