# Generated by Django 6.0.3 on 2026-03-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowwow', '0002_products_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='oldPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена без скидки'),
        ),
    ]
