# Generated by Django 6.0.3 on 2026-03-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowwow', '0003_products_oldprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название статьи')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('desc', models.CharField(verbose_name='Описание статьи')),
                ('views', models.IntegerField(verbose_name='Просмотры')),
                ('text', models.TextField(verbose_name='text')),
            ],
        ),
    ]
