# Generated by Django 6.0.3 on 2026-03-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowwow', '0004_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
