# Generated by Django 6.0.3 on 2026-03-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowwow', '0005_alter_articles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
