# Generated by Django 6.0.3 on 2026-03-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowwow', '0006_articles_image_alter_articles_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Категория статьи'),
        ),
    ]
