# Generated by Django 6.0.3 on 2026-03-31 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowwow', '0008_review_created_at'),
    ]

    operations = [
    ]
