# Generated by Django 6.0.3 on 2026-03-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowwow', '0009_auto_20260331_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва'),
        ),
    ]
